[WIP] Delete method of bookbag
stakater/workshop-operator pull request #28
Opened 2021-09-30 10:11 UTC by MaazMS

add delete method of bookbag

2021-09-30 10:16 UTC, stakater-user commented
@MaazMS Image is available for testing. `docker pull stakater/workshop-operator:SNAPSHOT-PR-28-020dac85`

2021-09-30 11:54 UTC, stakater-user commented
@MaazMS Image is available for testing. `docker pull stakater/workshop-operator:SNAPSHOT-PR-28-224003b2`

2021-09-30 12:40 UTC, stakater-user commented
@MaazMS Image is available for testing. `docker pull stakater/workshop-operator:SNAPSHOT-PR-28-663eaeb1`

2021-09-30 13:01 UTC, stakater-user commented
@MaazMS Image is available for testing. `docker pull stakater/workshop-operator:SNAPSHOT-PR-28-21231dec`

2021-09-30 13:54 UTC, stakater-user commented
@MaazMS Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/workshop-operator/commit/ab76ec9fa3a555487803c499ea0b57e22db944d7/checks) has Failed!

2021-10-02 18:18 UTC, stakater-user commented
@MaazMS Image is available for testing. `docker pull stakater/workshop-operator:SNAPSHOT-PR-28-acac29c8`

2021-12-03 14:00 UTC, stakater-user commented
@MaazMS Image is available for testing. `docker pull stakater/workshop-operator:SNAPSHOT-PR-28-0239f0e6`

2021-12-03 14:18 UTC, stakater-user commented
@MaazMS Image is available for testing. `docker pull stakater/workshop-operator:SNAPSHOT-PR-28-589bfdd3`

2021-12-05 08:00 UTC, stakater-user commented
@MaazMS Image is available for testing. `docker pull stakater/workshop-operator:SNAPSHOT-PR-28-16a7d022`

2021-12-05 08:48 UTC, stakater-user commented
@MaazMS Image is available for testing. `docker pull stakater/workshop-operator:SNAPSHOT-PR-28-0c90bb57`

2021-12-05 10:02 UTC, stakater-user commented
@MaazMS Image is available for testing. `docker pull stakater/workshop-operator:SNAPSHOT-PR-28-99ac9b0c`

2021-12-05 11:08 UTC, rasheedamir requested changes
check comments

2021-12-05 11:08 UTC, rasheedamir commented on controllers/bookbag_reconciler.go
> +	BOOKBAG_ROUTE             = 10080
not a good name

2021-12-05 11:54 UTC, stakater-user commented
@MaazMS Image is available for testing. `docker pull stakater/workshop-operator:SNAPSHOT-PR-28-e6e2a77d`

2021-12-05 16:32 UTC, rasheedamir approved these changes

2021-12-05 16:38 UTC, rasheedamir approved these changes

2021-12-05 16:38 UTC, merged